CREATE TABLE description_users (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_id integer,
    status text,
    city text,
    address text,
    ogrn text,
    inn text,
    activity text,
    date_registr text,
    constraint fk_description_users_users_id foreign key (name_id) references users (id)
    );