CREATE TABLE companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    link text UNIQUE,
    region_id integer, 
    constraint fk_users_region_id foreign key (region_id) references region (id)
);