CREATE TABLE description_companies (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name_id integer,
    status text,
    city text,
    manager text,
    address text,
    region_id integer,
    ogrn bigint UNIQUE,
    inn bigint UNIQUE,
    capital text,
    activity text,
    date_registr text,
    constraint fk_description_companies_companies_id foreign key (name_id) references companies (id)
    );